# -*- coding: utf-8 -*-
"""01- Area_da_circunferência.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mhs05JpB3xKLTxUomxHHbLfNeIsgaNcs
"""

# Conversor de Moeda: Reais para Dólares e Euros

# Dados fornecidos
valor_em_reais = 100.00
taxa_dolar = 5.60
taxa_euro = 6.60

# Conversões
valor_em_dolar = round(valor_em_reais / taxa_dolar, 2)
valor_em_euro = round(valor_em_reais / taxa_euro, 2)

# Exibição dos resultados
print(f"Valor em reais: R$ {valor_em_reais:.2f}")
print(f"Convertido para dólares: US$ {valor_em_dolar:.2f}")
print(f"Convertido para euros: € {valor_em_euro:.2f}")