# -*- coding: utf-8 -*-
"""02- Calculadora_de_Desconto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mhs05JpB3xKLTxUomxHHbLfNeIsgaNcs
"""

# Calculadora de Desconto

# Dados do produto
nome_produto = "Camiseta"
preco_original = 50.00
percentual_desconto = 20  # em %

# Cálculo do desconto
valor_desconto = round(preco_original * (percentual_desconto / 100), 2)
preco_final = round(preco_original - valor_desconto, 2)

# Exibição dos resultados
print(f"Produto: {nome_produto}")
print(f"Preço original: R$ {preco_original:.2f}")
print(f"Desconto aplicado: {percentual_desconto}%")
print(f"Valor do desconto: R$ {valor_desconto:.2f}")
print(f"Preço final com desconto: R$ {preco_final:.2f}")