# -*- coding: utf-8 -*-
"""03-Calculadora de Média Escolar .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mhs05JpB3xKLTxUomxHHbLfNeIsgaNcs
"""

# Calculadora de Média Escolar

# Notas do aluno
nota1 = 7.5
nota2 = 8.0
nota3 = 6.5

# Cálculo da média
media = round((nota1 + nota2 + nota3) / 3, 2)

# Exibição dos resultados
print("Notas do aluno:")
print(f"Nota 1: {nota1}")
print(f"Nota 2: {nota2}")
print(f"Nota 3: {nota3}")
print(f"Média final: {media}")