# -*- coding: utf-8 -*-
"""04- Calculadora_de_consumo_de_combustível .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mhs05JpB3xKLTxUomxHHbLfNeIsgaNcs
"""

# Calculadora de Consumo de Combustível

# Dados da viagem
distancia_percorrida = 300  # em km
combustivel_gasto = 25      # em litros

# Cálculo do consumo médio
consumo_medio = round(distancia_percorrida / combustivel_gasto, 2)

# Exibição dos resultados
print("Dados da viagem:")
print(f"Distância percorrida: {distancia_percorrida} km")
print(f"Combustível gasto: {combustivel_gasto} litros")
print(f"Consumo médio: {consumo_medio} km/l")