# -*- coding: utf-8 -*-
"""05-Calculadora de Soma com Entrada do Usuário.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mhs05JpB3xKLTxUomxHHbLfNeIsgaNcs
"""

# Calculadora de Soma com Entrada do Usuário

# Entrada dos valores
A = int(input("Digite o valor de A: "))
B = int(input("Digite o valor de B: "))

# Cálculo da soma
X = A + B

# Saída formatada
print(f"X = {X}")