# -*- coding: utf-8 -*-
"""06-Calculadora_de_salario_por_horas_trabalhadas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mhs05JpB3xKLTxUomxHHbLfNeIsgaNcs
"""

# Calculadora de Salário por Horas Trabalhadas

# Entrada dos dados
numero_funcionario = int(input("Digite o número do funcionário: "))
horas_trabalhadas = int(input("Digite a quantidade de horas trabalhadas: "))
valor_por_hora = float(input("Digite o valor recebido por hora (R$): "))

# Cálculo do salário
salario = round(horas_trabalhadas * valor_por_hora, 2)

# Saída formatada
print(f"Número do funcionário = {numero_funcionario}")
print(f"Salário = R$ {salario:.2f}")