# -*- coding: utf-8 -*-
"""1.senha_aleatoria

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ue1ejnZMOwpztVGLthtikWOICX9HBTTv
"""

import random
import string

def gerar_senha(tamanho: int) -> str:
    """
    Gera uma senha aleatória com caracteres especiais, letras e números.

    Args:
        tamanho (int): Quantidade de caracteres desejada para a senha.

    Returns:
        str: Senha gerada aleatoriamente.
    """
    # Define o conjunto de caracteres permitidos (letras, dígitos e símbolos)
    caracteres = string.ascii_letters + string.digits + string.punctuation

    # Gera a senha aleatória com o tamanho especificado
    senha = ''.join(random.choice(caracteres) for _ in range(tamanho))

    return senha


# Interface interativa para entrada do usuário
if __name__ == "__main__":
    try:
        # Solicita ao usuário o tamanho da senha
        tamanho = int(input("Digite o número de caracteres da senha: "))

        # Gera e exibe a senha
        senha_gerada = gerar_senha(tamanho)
        print(f"Senha gerada: {senha_gerada}")

    except ValueError:
        # Trata entradas inválidas
        print("Erro: Por favor, insira um número inteiro válido.")

