# -*- coding: utf-8 -*-
"""2.perfil_usuario_aleatorio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ue1ejnZMOwpztVGLthtikWOICX9HBTTv
"""

import requests

def gerar_perfil_usuario() -> dict:
    """
    Gera um perfil de usuário aleatório usando a API Random User Generator.

    Returns:
        dict: Dicionário contendo nome completo, email e país do usuário.
    """
    # Faz uma requisição GET à API
    resposta = requests.get("https://randomuser.me/api/")

    # Verifica se a requisição foi bem-sucedida
    if resposta.status_code == 200:
        dados = resposta.json()
        usuario = dados['results'][0]

        # Extrai nome, email e país
        nome_completo = f"{usuario['name']['first']} {usuario['name']['last']}"
        email = usuario['email']
        pais = usuario['location']['country']

        return {
            "nome": nome_completo,
            "email": email,
            "pais": pais
        }
    else:
        raise Exception("Erro ao acessar a API Random User Generator.")


# Interface interativa para exibir o perfil gerado
if __name__ == "__main__":
    try:
        perfil = gerar_perfil_usuario()
        print("Perfil de usuário gerado:")
        print(f"Nome: {perfil['nome']}")
        print(f"Email: {perfil['email']}")
        print(f"País: {perfil['pais']}")
    except Exception as e:
        print(f"Erro: {e}")

