# -*- coding: utf-8 -*-
"""3.consultar_endereco_por_cep

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ue1ejnZMOwpztVGLthtikWOICX9HBTTv
"""

import requests

def consultar_endereco_por_cep(cep: str) -> dict:
    """
    Consulta informações de endereço a partir de um CEP usando a API ViaCEP.

    Args:
        cep (str): CEP brasileiro no formato '00000000' ou '00000-000'.

    Returns:
        dict: Dicionário com logradouro, bairro, cidade e estado.
    """
    # Remove traços e espaços do CEP
    cep_limpo = cep.replace("-", "").strip()

    # URL da API ViaCEP
    url = f"https://viacep.com.br/ws/{cep_limpo}/json/"

    # Faz a requisição GET
    resposta = requests.get(url)

    # Verifica se a requisição foi bem-sucedida
    if resposta.status_code == 200:
        dados = resposta.json()

        # Verifica se o CEP é válido
        if "erro" in dados:
            raise ValueError("CEP não encontrado.")

        # Extrai os dados desejados
        return {
            "logradouro": dados.get("logradouro", ""),
            "bairro": dados.get("bairro", ""),
            "cidade": dados.get("localidade", ""),
            "estado": dados.get("uf", "")
        }
    else:
        raise Exception("Erro ao consultar a API ViaCEP.")


# Interface interativa para entrada do usuário
if __name__ == "__main__":
    try:
        # Solicita o CEP ao usuário
        cep_input = input("Digite o CEP (ex: 01001-000): ")

        # Consulta o endereço
        endereco = consultar_endereco_por_cep(cep_input)

        # Exibe os dados formatados
        print("Endereço encontrado:")
        print(f"Logradouro: {endereco['logradouro']}")
        print(f"Bairro: {endereco['bairro']}")
        print(f"Cidade: {endereco['cidade']}")
        print(f"Estado: {endereco['estado']}")

    except ValueError as ve:
        print(f"Erro: {ve}")
    except Exception as e:
        print(f"Erro inesperado: {e}")

