# -*- coding: utf-8 -*-
"""4.cotação_cambio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ue1ejnZMOwpztVGLthtikWOICX9HBTTv
"""

import requests
from datetime import datetime

def consultar_cotacao(moeda: str) -> dict:
    """
    Consulta a cotação atual de uma moeda estrangeira em relação ao Real Brasileiro (BRL)
    usando a API da AwesomeAPI.

    Args:
        moeda (str): Código da moeda estrangeira (ex: USD, EUR, GBP).

    Returns:
        dict: Dicionário com valor atual, máximo, mínimo e data/hora da última atualização.
    """
    moeda = moeda.upper().strip()
    url = f"https://economia.awesomeapi.com.br/json/last/{moeda}-BRL"

    try:
        resposta = requests.get(url, timeout=5)
        resposta.raise_for_status()
        dados = resposta.json()

        chave = f"{moeda}BRL"
        if chave not in dados:
            raise ValueError("Moeda não encontrada ou não disponível na API.")

        info = dados[chave]
        return {
            "moeda": info["name"],
            "valor_atual": float(info["bid"]),
            "valor_maximo": float(info["high"]),
            "valor_minimo": float(info["low"]),
            "atualizacao": datetime.fromtimestamp(int(info["timestamp"])).strftime("%d/%m/%Y %H:%M:%S")
        }

    except requests.exceptions.HTTPError:
        raise ConnectionError("Falha na conexão com a API. Verifique o código da moeda.")
    except requests.exceptions.RequestException:
        raise ConnectionError("Erro de rede ou tempo limite excedido.")
    except ValueError as ve:
        raise ve
    except Exception:
        raise RuntimeError("Erro inesperado ao processar os dados da API.")


# Interface interativa para entrada do usuário
if __name__ == "__main__":
    try:
        codigo = input("Digite o código da moeda estrangeira (ex: USD, EUR, GBP): ")
        cotacao = consultar_cotacao(codigo)

        print(f"\nCotação de {cotacao['moeda']}:")
        print(f"Valor atual: R$ {cotacao['valor_atual']:.2f}")
        print(f"Valor máximo: R$ {cotacao['valor_maximo']:.2f}")
        print(f"Valor mínimo: R$ {cotacao['valor_minimo']:.2f}")
        print(f"Última atualização: {cotacao['atualizacao']}")

    except ValueError as ve:
        print(f"Erro: {ve}")
    except ConnectionError as ce:
        print(f"Erro de conexão: {ce}")
    except RuntimeError as re:
        print(f"Erro inesperado: {re}")

