# -*- coding: utf-8 -*-
"""01-Programa_saudacao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NYINCdAHbjl-5lYLzE_6cTRWlKGFxiaj
"""

#Crie um programa que imprima a mensagem "Hello, world!" na tela.
print("Hello, world!")