# -*- coding: utf-8 -*-
"""02-02-Calculadora_de_soma.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NYINCdAHbjl-5lYLzE_6cTRWlKGFxiaj
"""

# Desenvolva um programa que soma dois números.
# Use as variáveis numero1 = 12 e numero2 = 14.
# O programa deve calcular a soma e exibir o resultado.

numero1 = 12
numero2 = 14

def _soma(x, y):
    soma = numero1 + numero2
    print(" O valor da soma é: " + str(soma))

_soma(numero1, numero2)