# -*- coding: utf-8 -*-
"""1. Calculo_desvio_padrao

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ue1ejnZMOwpztVGLthtikWOICX9HBTTv
"""

import re
import statistics

def extrair_tempos_execucao(caminho_arquivo: str) -> list:
    """
    Lê um arquivo de log e extrai os tempos de execução dos treinamentos.

    Args:
        caminho_arquivo (str): Caminho para o arquivo de log.

    Returns:
        list: Lista de tempos de execução em segundos (float).
    """
    tempos = []

    # Expressão regular para capturar tempos como "Tempo de execução: 12.34s"
    padrao = re.compile(r"Tempo de execução:\s*([\d.]+)s")

    with open(caminho_arquivo, "r", encoding="utf-8") as arquivo:
        for linha in arquivo:
            match = padrao.search(linha)
            if match:
                tempo = float(match.group(1))
                tempos.append(tempo)

    return tempos


def calcular_estatisticas(tempos: list) -> dict:
    """
    Calcula a média e o desvio padrão dos tempos de execução.

    Args:
        tempos (list): Lista de tempos em segundos.

    Returns:
        dict: Dicionário com média e desvio padrão.
    """
    if not tempos:
        raise ValueError("Nenhum tempo de execução encontrado no arquivo.")

    media = statistics.mean(tempos)
    desvio_padrao = statistics.stdev(tempos)

    return {
        "media": round(media, 2),
        "desvio_padrao": round(desvio_padrao, 2)
    }


# Interface interativa
if __name__ == "__main__":
    try:
        caminho = input("Digite o caminho do arquivo de log: ")
        tempos = extrair_tempos_execucao(caminho)
        estatisticas = calcular_estatisticas(tempos)

        print("\nEstatísticas de tempo de execução:")
        print(f"Média: {estatisticas['media']} segundos")
        print(f"Desvio padrão: {estatisticas['desvio_padrao']} segundos")

    except FileNotFoundError:
        print("Erro: Arquivo não encontrado.")
    except ValueError as ve:
        print(f"Erro: {ve}")
    except Exception as e:
        print(f"Erro inesperado: {e}")

