# -*- coding: utf-8 -*-
"""2.arquivo_CSV

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ue1ejnZMOwpztVGLthtikWOICX9HBTTv
"""

import csv

def escrever_dados_csv(caminho_arquivo: str, dados: list):
    """
    Escreve dados pessoais em um arquivo CSV.

    Args:
        caminho_arquivo (str): Caminho do arquivo CSV a ser criado.
        dados (list): Lista de dicionários com informações pessoais.
    """
    # Define os nomes das colunas
    campos = ["Nome", "Idade", "Cidade"]

    # Abre o arquivo para escrita
    with open(caminho_arquivo, mode="w", newline="", encoding="utf-8") as arquivo_csv:
        escritor = csv.DictWriter(arquivo_csv, fieldnames=campos)

        # Escreve o cabeçalho
        escritor.writeheader()

        # Escreve os dados
        for pessoa in dados:
            escritor.writerow(pessoa)


# Interface interativa
if __name__ == "__main__":
    # Exemplo de dados
    pessoas = [
        {"Nome": "Ana Silva", "Idade": 28, "Cidade": "São Paulo"},
        {"Nome": "Carlos Souza", "Idade": 35, "Cidade": "Rio de Janeiro"},
        {"Nome": "Mariana Lima", "Idade": 22, "Cidade": "Belo Horizonte"}
    ]

    caminho = "dados_pessoais.csv"
    escrever_dados_csv(caminho, pessoas)
    print(f"Arquivo '{caminho}' criado com sucesso!")

