# -*- coding: utf-8 -*-
"""3.leitor_dados_csv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ue1ejnZMOwpztVGLthtikWOICX9HBTTv
"""

import csv

def ler_dados_csv(caminho_arquivo: str):
    """
    Lê um arquivo CSV contendo informações de pessoas e exibe os dados na tela.

    Args:
        caminho_arquivo (str): Caminho do arquivo CSV.
    """
    try:
        with open(caminho_arquivo, mode="r", encoding="utf-8") as arquivo_csv:
            leitor = csv.DictReader(arquivo_csv)

            print("Dados encontrados no arquivo:")
            for linha in leitor:
                nome = linha.get("Nome", "")
                idade = linha.get("Idade", "")
                cidade = linha.get("Cidade", "")
                print(f"Nome: {nome}, Idade: {idade}, Cidade: {cidade}")

    except FileNotFoundError:
        print("Erro: Arquivo não encontrado.")
    except Exception as e:
        print(f"Erro inesperado: {e}")


# Interface interativa
if __name__ == "__main__":
    caminho = input("Digite o caminho do arquivo CSV: ")
    ler_dados_csv(caminho)

