# -*- coding: utf-8 -*-
"""4.escrever_json

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ue1ejnZMOwpztVGLthtikWOICX9HBTTv
"""

import json

def escrever_json(caminho_arquivo: str, dados: dict):
    """
    Escreve dados de uma pessoa em um arquivo JSON.

    Args:
        caminho_arquivo (str): Caminho do arquivo JSON.
        dados (dict): Dicionário com os dados da pessoa.
    """
    with open(caminho_arquivo, "w", encoding="utf-8") as arquivo:
        json.dump(dados, arquivo, indent=4, ensure_ascii=False)


def ler_json(caminho_arquivo: str) -> dict:
    """
    Lê os dados de uma pessoa a partir de um arquivo JSON.

    Args:
        caminho_arquivo (str): Caminho do arquivo JSON.

    Returns:
        dict: Dicionário com os dados da pessoa.
    """
    with open(caminho_arquivo, "r", encoding="utf-8") as arquivo:
        return json.load(arquivo)


# Interface interativa
if __name__ == "__main__":
    # Dados de exemplo
    pessoa = {
        "nome": "João Pereira",
        "idade": 30,
        "cidade": "Curitiba"
    }

    caminho = "pessoa.json"

    # Escreve os dados no arquivo
    escrever_json(caminho, pessoa)
    print(f"Dados salvos em '{caminho}'.")

    # Lê os dados do arquivo
    dados_lidos = ler_json(caminho)
    print("\nDados lidos do arquivo JSON:")
    print(f"Nome: {dados_lidos['nome']}")
    print(f"Idade: {dados_lidos['idade']}")
    print(f"Cidade: {dados_lidos['cidade']}")

