# -*- coding: utf-8 -*-
"""01-Calculadora_de_area_da_circunferência

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mhs05JpB3xKLTxUomxHHbLfNeIsgaNcs
"""

# Calculadora de Área da Circunferência

# Constante π
pi = 3.14159265

# Entrada do usuário
raio = float(input("Digite o valor do raio: "))

# Cálculo da área
area = pi * raio ** 2

# Saída formatada com 4 casas decimais
print(f"A= {area:.4f}")