# -*- coding: utf-8 -*-
"""02- Classificador_de_Idade

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mhs05JpB3xKLTxUomxHHbLfNeIsgaNcs
"""

# Classificador de Idade

# Entrada da idade
idade = int(input("Digite sua idade: "))

# Classificação
if idade >= 0 and idade <= 12:
    categoria = "Criança"
elif idade >= 13 and idade <= 17:
    categoria = "Adolescente"
elif idade >= 18 and idade <= 59:
    categoria = "Adulto"
elif idade >= 60:
    categoria = "Idoso"
else:
    categoria = "Idade inválida"

# Saída
print(f"Classificação: {categoria}")