# -*- coding: utf-8 -*-
"""04- Conversor_de_temperatura

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mhs05JpB3xKLTxUomxHHbLfNeIsgaNcs
"""

# Conversor de Temperatura

# Função de conversão
def converter_temperatura(valor, origem, destino):
    origem = origem.lower()
    destino = destino.lower()

    # Converter origem para Celsius
    if origem == "celsius":
        celsius = valor
    elif origem == "fahrenheit":
        celsius = (valor - 32) * 5 / 9
    elif origem == "kelvin":
        celsius = valor - 273.15
    else:
        return "Unidade de origem inválida."

    # Converter Celsius para destino
    if destino == "celsius":
        return round(celsius, 2)
    elif destino == "fahrenheit":
        return round((celsius * 9 / 5) + 32, 2)
    elif destino == "kelvin":
        return round(celsius + 273.15, 2)
    else:
        return "Unidade de destino inválida."

# Entrada do usuário
valor = float(input("Digite a temperatura: "))
origem = input("Digite a unidade de origem (Celsius, Fahrenheit, Kelvin): ")
destino = input("Digite a unidade de destino (Celsius, Fahrenheit, Kelvin): ")

# Conversão e saída
resultado = converter_temperatura(valor, origem, destino)
print(f"\nTemperatura convertida: {resultado} {destino.capitalize()}")