# -*- coding: utf-8 -*-
"""05-Verificador_de_ano_bissexto

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mhs05JpB3xKLTxUomxHHbLfNeIsgaNcs
"""

# Verificador de Ano Bissexto

# Entrada do usuário
ano = int(input("Digite o ano: "))

# Verificação de bissexto
if (ano % 4 == 0 and ano % 100 != 0) or (ano % 400 == 0):
    resultado = "Ano bissexto"
else:
    resultado = "Ano comum"

# Saída
print(f"{ano} é um {resultado}.")