# -*- coding: utf-8 -*-
"""06- Calculadora_de_comissão

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mhs05JpB3xKLTxUomxHHbLfNeIsgaNcs
"""

# Calculadora de Comissão

# Entrada dos dados
nome_vendedor = input("Digite o nome do vendedor: ")
salario_fixo = float(input("Digite o salário fixo (R$): "))
vendas_mes = float(input("Digite o total de vendas do mês (R$): "))

# Cálculo da comissão e total a receber
comissao = vendas_mes * 0.15
total_receber = round(salario_fixo + comissao, 2)

# Saída formatada
print(f"\nVendedor: {nome_vendedor}")
print(f"Total a receber = R$ {total_receber:.2f}")