# -*- coding: utf-8 -*-
"""07- Calculadora_da_media

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mhs05JpB3xKLTxUomxHHbLfNeIsgaNcs
"""

# Calculadora da Média com Exame

# Entrada das quatro notas com uma casa decimal
N1 = float(input())
N2 = float(input())
N3 = float(input())
N4 = float(input())

# Cálculo da média ponderada
media = (N1 * 2 + N2 * 3 + N3 * 4 + N4 * 1) / 10
print(f"Media: {media:.1f}")

# Verificação da situação do aluno
if media >= 7.0:
    print("Aluno aprovado.")
elif media < 5.0:
    print("Aluno reprovado.")
else:
    print("Aluno em exame.")
    nota_exame = float(input())
    print(f"Nota do exame: {nota_exame:.1f}")
    media_final = (media + nota_exame) / 2
    if media_final >= 5.0:
        print("Aluno aprovado.")
    else:
        print("Aluno reprovado.")
    print(f"Media final: {media_final:.1f}")