# -*- coding: utf-8 -*-
"""1.calculadora_de_gorjeta

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ue1ejnZMOwpztVGLthtikWOICX9HBTTv
"""

def calcular_gorjeta(valor_conta: float, porcentagem_gorjeta: float) -> float:
    """
    Calcula o valor da gorjeta com base no valor da conta e na porcentagem desejada.

    Args:
        valor_conta (float): Valor total da conta do restaurante.
        porcentagem_gorjeta (float): Porcentagem da gorjeta (ex: 10 para 10%).

    Returns:
        float: Valor da gorjeta calculada.
    """
    return valor_conta * (porcentagem_gorjeta / 100)


# Interface interativa para entrada de dados via terminal (ideal para Google Colab)
if __name__ == "__main__":
    try:
        # Solicita ao usuário o valor da conta
        valor = float(input("Digite o valor da conta (R$): "))

        # Solicita ao usuário a porcentagem da gorjeta
        porcentagem = float(input("Digite a porcentagem da gorjeta (%): "))

        # Calcula a gorjeta usando a função definida
        gorjeta = calcular_gorjeta(valor, porcentagem)

        # Exibe o resultado formatado com duas casas decimais
        print(f"Gorjeta: R$ {gorjeta:.2f}")

    except ValueError:
        # Trata entradas inválidas (não numéricas)
        print("Erro: Por favor, insira números válidos.")