# -*- coding: utf-8 -*-
"""2.detector_de_palindromo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ue1ejnZMOwpztVGLthtikWOICX9HBTTv
"""

import re

def eh_palindromo(texto: str) -> bool:
    """
    Verifica se uma palavra ou frase é um palíndromo, ignorando espaços e pontuação.

    Args:
        texto (str): Palavra ou frase a ser verificada.

    Returns:
        bool: True se for palíndromo, False caso contrário.
    """
    # Remove espaços, pontuação e transforma em minúsculas
    texto_limpo = re.sub(r'[^a-zA-Z0-9]', '', texto).lower()

    # Compara o texto com sua versão invertida
    return texto_limpo == texto_limpo[::-1]


# Interface interativa para entrada do usuário
if __name__ == "__main__":
    entrada = input("Digite uma palavra ou frase: ")

    # Verifica se é palíndromo e imprime resposta personalizada
    if eh_palindromo(entrada):
        print("Sim")
    else:
        print("Não")