# -*- coding: utf-8 -*-
"""3.calculo_preco_com_desconto

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ue1ejnZMOwpztVGLthtikWOICX9HBTTv
"""

def calcular_preco_com_desconto(preco_original: float, percentual_desconto: float) -> float:
    """
    Calcula o preço final de um produto após aplicar o desconto.

    Args:
        preco_original (float): Preço original do produto.
        percentual_desconto (float): Percentual de desconto a ser aplicado (ex: 10 para 10%).

    Returns:
        float: Preço final com desconto aplicado.
    """
    # Calcula o valor do desconto
    valor_desconto = preco_original * (percentual_desconto / 100)

    # Subtrai o desconto do preço original
    preco_final = preco_original - valor_desconto

    return round(preco_final, 2)  # Arredonda para duas casas decimais


# Interface interativa para entrada do usuário
if __name__ == "__main__":
    try:
        # Solicita o preço original do produto
        preco = float(input("Digite o preço original do produto (R$): "))

        # Solicita o percentual de desconto
        desconto = float(input("Digite o percentual de desconto (%): "))

        # Calcula o preço final com desconto
        preco_final = calcular_preco_com_desconto(preco, desconto)

        # Exibe o resultado formatado
        print(f"Preço final com desconto: R$ {preco_final:.2f}")

    except ValueError:
        # Trata entradas inválidas
        print("Erro: Por favor, insira números válidos.")