# -*- coding: utf-8 -*-
"""4.calculadora_idade

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ue1ejnZMOwpztVGLthtikWOICX9HBTTv
"""

from datetime import date

def calcular_idade_em_dias(ano_nascimento: int) -> int:
    """
    Calcula a idade de uma pessoa em dias com base no ano de nascimento.

    Args:
        ano_nascimento (int): Ano de nascimento da pessoa (ex: 1990).

    Returns:
        int: Idade aproximada em dias.
    """
    # Obtém o ano atual
    ano_atual = date.today().year

    # Calcula a idade em anos
    idade_anos = ano_atual - ano_nascimento

    # Converte a idade em dias (aproximação: 365 dias por ano)
    idade_dias = idade_anos * 365

    return idade_dias


# Interface interativa para entrada do usuário
if __name__ == "__main__":
    try:
        # Solicita o ano de nascimento
        ano = int(input("Digite o ano de nascimento: "))

        # Calcula a idade em dias
        idade_dias = calcular_idade_em_dias(ano)

        # Exibe o resultado
        print(f"Idade aproximada em dias: {idade_dias}")

    except ValueError:
        # Trata entradas inválidas
        print("Erro: Por favor, insira um ano válido.")