# -*- coding: utf-8 -*-
"""01-Calculadora_quatro_operacoes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NYINCdAHbjl-5lYLzE_6cTRWlKGFxiaj
"""

# EXERCÍCIO PRÁTICO 1 - Calculadora com tratamento de erros
# Descrição: Calculadora que realiza operações básicas (+, -, *, /) entre dois números,
# com tratamento de erros para entradas inválidas, divisão por zero e operação inválida.

while True:
    try:
        # Solicita o primeiro número ao usuário
        num1 = float(input("Digite o primeiro número: "))

        # Solicita o segundo número ao usuário
        num2 = float(input("Digite o segundo número: "))

        # Solicita a operação desejada
        operacao = input("Digite a operação (+, -, *, /): ")

        # Verifica se a operação é válida
        if operacao not in ['+', '-', '*', '/']:
            raise ValueError("Operação inválida. Use apenas +, -, * ou /.")

        # Verifica se há tentativa de divisão por zero
        if operacao == '/' and num2 == 0:
            raise ZeroDivisionError("Divisão por zero não é permitida.")

        # Realiza a operação conforme o operador informado
        if operacao == '+':
            resultado = num1 + num2
        elif operacao == '-':
            resultado = num1 - num2
        elif operacao == '*':
            resultado = num1 * num2
        elif operacao == '/':
            resultado = num1 / num2

        # Exibe o resultado da operação
        print(f"Resultado: {num1} {operacao} {num2} = {resultado}")

        # Encerra o loop após operação bem-sucedida
        break

    # Trata erro de entrada não numérica
    except ValueError as ve:
        print(f"Erro: {ve}. Tente novamente.")

    # Trata erro de divisão por zero
    except ZeroDivisionError as zde:
        print(f"Erro: {zde}. Tente novamente.")