# -*- coding: utf-8 -*-
"""02-registro_de_notas_alunos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NYINCdAHbjl-5lYLzE_6cTRWlKGFxiaj
"""

# EXERCÍCIO PRÁTICO 2 - Registro de notas com cálculo de média
# Descrição: Programa que permite a um professor registrar notas de alunos.
# O programa aceita notas entre 0 e 10, ignora entradas inválidas e calcula a média ao final.

# Lista para armazenar as notas válidas
notas = []

print("Digite as notas dos alunos (de 0 a 10). Para encerrar, digite 'fim'.")

while True:
    entrada = input("Nota: ")

    # Verifica se o usuário deseja encerrar o programa
    if entrada.lower() == 'fim':
        break

    try:
        # Tenta converter a entrada para float
        nota = float(entrada)

        # Verifica se a nota está no intervalo permitido
        if 0 <= nota <= 10:
            notas.append(nota)
        else:
            print("Nota inválida. Digite um valor entre 0 e 10.")

    # Trata erro de conversão para número
    except ValueError:
        print("Entrada inválida. Digite um número ou 'fim' para encerrar.")

# Verifica se há notas registradas antes de calcular a média
if len(notas) > 0:
    media = sum(notas) / len(notas)
    print(f"\nMédia da turma: {media:.2f}")
else:
    print("\nNenhuma nota válida foi registrada.")