# -*- coding: utf-8 -*-
"""03-verificador_senha_forte.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NYINCdAHbjl-5lYLzE_6cTRWlKGFxiaj
"""

# EXERCÍCIO PRÁTICO 3 - Verificador de senha forte com bloqueio de sequência
# Descrição: Programa que verifica se uma senha é forte.
# Regras:
# - Mínimo de 8 caracteres
# - Deve conter pelo menos um número
# - Não pode conter a sequência "12345678"
# O programa continua solicitando senhas até que uma válida seja inserida ou o usuário digite 'sair'.

import re  # Importa o módulo de expressões regulares para verificar presença de números

print("Verificador de senha forte")
print("Regras:")
print("- Mínimo de 8 caracteres")
print("- Deve conter pelo menos um número")
print("- Não pode conter a sequência '12345678'")
print("Digite 'sair' para encerrar.\n")

while True:
    senha = input("Digite sua senha: ")

    # Permite encerrar o programa
    if senha.lower() == 'sair':
        print("Encerrando o verificador.")
        break

    # Verifica o comprimento mínimo
    if len(senha) < 8:
        print("Senha fraca: deve conter pelo menos 8 caracteres.\n")
        continue

    # Verifica se contém pelo menos um número
    if not re.search(r'\d', senha):
        print("Senha fraca: deve conter pelo menos um número.\n")
        continue

    # Verifica se contém a sequência proibida "12345678"
    if "12345678" in senha:
        print("Senha fraca: não pode conter a sequência '12345678'.\n")
        continue

    # Se passou por todas as verificações, a senha é considerada forte
    print("Senha forte! ✅")
    break