# -*- coding: utf-8 -*-
"""03-verificador_numeros_pares_e_impares.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NYINCdAHbjl-5lYLzE_6cTRWlKGFxiaj
"""

# EXERCÍCIO PRÁTICO 4 - Verificador de números pares e ímpares
# Descrição: Programa que solicita números inteiros ao usuário.
# Para cada número inserido, informa se é par ou ímpar.
# O programa continua até que o usuário digite 'fim'.
# Ao final, exibe a quantidade total de números pares e ímpares inseridos.

# Inicializa contadores
pares = 0
impares = 0

print("Digite números inteiros. Para encerrar, digite 'fim'.\n")

while True:
    entrada = input("Número: ")

    # Verifica se o usuário deseja encerrar
    if entrada.lower() == 'fim':
        break

    try:
        # Tenta converter a entrada para inteiro
        numero = int(entrada)

        # Verifica se o número é par ou ímpar
        if numero % 2 == 0:
            print("→ Par\n")
            pares += 1
        else:
            print("→ Ímpar\n")
            impares += 1

    # Trata erro de entrada não numérica
    except ValueError:
        print("Entrada inválida. Digite apenas números inteiros ou 'fim' para encerrar.\n")

# Exibe o resumo final
print("Encerrado.")
print(f"Total de números pares: {pares}")
print(f"Total de números ímpares: {impares}")